import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} main`}>
        <div className={styles.center}>
          <h1>Demonstração Tech Talks</h1>
        </div>

        <div className={styles.grid}>
          <a href="/imagem" className={styles.card}>
            <h2>
              Imagens <span>-&gt;</span>
            </h2>
            <p>Comparação WebP usando o componente do NextJS e PNG.</p>
          </a>

          <a href="/server-side" className={styles.card}>
            <h2>
              SSR <span>-&gt;</span>
            </h2>
            <p>Página renderizando utilizando requisição pelo servidor.</p>
          </a>

          <a href="/client-side" className={styles.card}>
            <h2>
              CSR <span>-&gt;</span>
            </h2>
            <p>Página renderizando utilizando requisição pelo browser.</p>
          </a>
        </div>
      </main>
    </>
  )
}
